# Generated by Django 6.0.2 on 2026-03-02 14:04

import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(validators=[ledger.models.biolength_validation]),
        ),
    ]
