# Generated by Django 6.0.2 on 2026-03-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
